mamba:
    ssm_type: "S6-Real"
    n_layers: 1
    d_model: 128
    d_state: 16
    d_conv: 4
    expand_factor: 2
    bidirectional: False
    dt_is_selective: True
    B_is_selective: True
    C_is_selective: True
    deterministic: False
    pscan: False
    initA_real: "S4"
    channel_sharing: True
    dt_rank: 'auto'
    use_cuda: True

model:
  img_channels: 3
  patch_size: 4
  num_classes: 10

train:
  batch_size: 50
  lr: 1e-5
  weight_decay: 1e-5
  epochs: 2000
